"""
Train HMM session model from synthetic session CSV data.

Reads: data/raw/session_data/sessions.csv
       (generated by scripts/create_synthetic_data_local.py)
Saves: models/checkpoints/hmm.pkl

Usage:
    cd <project root>
    python scripts/train_hmm.py
"""
import sys
import pandas as pd
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.session.hmm import SessionHMM

# Intents that indicate malicious/suspicious session behaviour
MALICIOUS_INTENTS = {
    "grooming", "gaslighting", "social_engineering",
    "direct_attack", "threatening", "escalating_aggression",
    "baiting", "passive_hostility", "irony", "sarcasm",
    "topic_deflection", "denial", "identity_concealment",
}

CSV_PATH  = Path("data/raw/session_data/sessions.csv")
SAVE_PATH = Path("models/checkpoints/hmm.pkl")


def main():
    if not CSV_PATH.exists():
        print(f"Session data not found at {CSV_PATH}")
        print("Run scripts/create_synthetic_data_local.py first.")
        sys.exit(1)

    # ── Load ────────────────────────────────────────────────────────────────
    df = pd.read_csv(CSV_PATH)
    n_sessions = df["session_id"].nunique()
    print(f"Loaded {len(df):,} turns across {n_sessions:,} sessions")

    # ── Convert to HMM format ───────────────────────────────────────────────
    sessions = []
    for session_id, group in df.groupby("session_id"):
        group = group.sort_values("turn_id")
        intents = group["intent"].tolist()
        has_toxic   = bool(group["toxic"].any())
        has_malicious = any(i in MALICIOUS_INTENTS for i in intents)
        label = "malicious_session" if (has_toxic or has_malicious) else "benign_session"
        sessions.append({"intents": intents, "label": label})

    benign    = sum(1 for s in sessions if s["label"] == "benign_session")
    malicious = len(sessions) - benign
    print(f"Session labels — benign: {benign} | malicious: {malicious}")

    # ── Train ────────────────────────────────────────────────────────────────
    hmm = SessionHMM(n_iter=100, tol=1e-4)
    hmm.fit(sessions)

    # ── Save ─────────────────────────────────────────────────────────────────
    hmm.save(SAVE_PATH)

    # ── Sanity checks ────────────────────────────────────────────────────────
    print("\nSanity checks:")
    tests = [
        (["greeting", "question", "information_sharing", "feedback"],              "LOW"),
        (["greeting", "small_talk", "question"] * 3,                               "LOW"),
        (["greeting", "question", "grooming", "threatening", "identity_concealment"], "HIGH"),
        (["greeting", "small_talk", "venting", "baiting", "direct_attack"],        "HIGH"),
        (["solidarity_seeking", "venting", "gaslighting", "social_engineering"],   "HIGH"),
    ]
    for seq, expected in tests:
        risk = hmm.compute_risk(seq)
        verdict = "HIGH" if risk >= 0.5 else "LOW"
        match = "✓" if verdict == expected else "✗"
        print(f"  {match} {seq[:3]}...  risk={risk:.3f}  (expected {expected})")


if __name__ == "__main__":
    main()
